server:
  port: 8099
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

server-resource:
  uploadFolder: E:/work/graduate/recipeResources/

spring:
  application:
    name: recipeBE
  profiles:
    active: prod
  banner:
    location: classpath:banner/banner.txt
  servlet:
    multipart:
      max-file-size: 100MB      # 文件上传大小限制，设置最大值，不能超过该值，否则报错  max-file-size: 500KB
      max-request-size: 100MB     # 文件最大请求限制，用于批量上传 max-request-size: 500KB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_recipe?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
  redis: # redis配置
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: xiaoxi
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

# 整合mybatis mybatis.configuration.map-underscore-to-camel-case= true
mybatis:
  type-aliases-package: com.xi.model.pojo                   # 所有pojo类所在的包路径
  mapper-locations: classpath:com/xi/mapper/xml/*.xml # mapper映射文件
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  mapper-locations: classpath:com/xi/mapper/xml/*.xml

# 分页插件助手的配置
pagehelper:
  helper-dialect: MYSQL
  support-methods-arguments: true


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒 设置：30min
  activity-timeout: 1800
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

# 日志级别
logging:
  level:
    root: info

